gramineproject/contrib

- .readthedocs.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/1)
> [Docs] Add .readthedocs.yaml

- Documentation/requirements.txt
Same problem as in https://github.com/gramineproject/gramine/pull/493.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/4)
> [Docs] Pin jinja2<3.1

- Examples/aks-python-helloworld/README.md
- Examples/aks-python-helloworld/gsc-aks-python-deployment.yaml
- Examples/aks-python-helloworld/python.manifest
Signed-off-by: aneessahib <anees.a.sahib@intel.com>
Add example to deploy a gsc python image to AKS cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/6)
> Add example to deploy a gsc python image to AKS cluster

- Curated-Apps/curate.py
- Curated-Apps/verifier/verifier.dockerfile.template
Workaround for the packaging issue with v1.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/9)
> Workaround for the packaging issue with v1.3

- Curated-Apps/README.md
- Curated-Apps/curate.py
- Curated-Apps/util/curation_script.sh
- Curated-Apps/workloads/redis/redis-gsc.dockerfile.template
- Curated-Apps/workloads/sklearn/.gitignore
- Curated-Apps/workloads/sklearn/README.md
- Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile
- Curated-Apps/workloads/sklearn/base_image_helper/README.md
- Curated-Apps/workloads/sklearn/base_image_helper/download_dataset.py
- Curated-Apps/workloads/sklearn/base_image_helper/helper.sh
- Curated-Apps/workloads/sklearn/base_image_helper/kmeans_perf_eval.py
- Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template
- Curated-Apps/workloads/sklearn/sklearn.manifest.template
Updating the Curated script and packages to add `Intel® extension for Scikit-learn` app
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/12)
> Updating the Curated script and packages to add Intel® extension for Scikit-learn app

- Integrations/azure/akv-sign/gramine-sgx-akv-sign
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/17)
> Update AKV sign script to reflect tomli changes

- Curated-Apps/util/config.yaml.template
- Curated-Apps/verifier/verifier.dockerfile.template
- Curated-Apps/workloads/pytorch/base_image_helper/Dockerfile
- Curated-Apps/workloads/pytorch/pytorch-gsc.dockerfile.template
- Curated-Apps/workloads/pytorch/pytorch.manifest.template
- Curated-Apps/workloads/redis/redis-gsc.dockerfile.template
- Curated-Apps/workloads/redis/redis.manifest.template
- Curated-Apps/workloads/sklearn/base_image_helper/Dockerfile
- Curated-Apps/workloads/sklearn/sklearn-gsc.dockerfile.template
- Curated-Apps/workloads/sklearn/sklearn.manifest.template
Added copyright info in the files which are missing copyright info.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/22)
> [Curated-Apps] Add copyright info

- Curated-Apps/curate.py
- Curated-Apps/workloads/tensorflow-serving/.gitignore
- Curated-Apps/workloads/tensorflow-serving/README.md
- Curated-Apps/workloads/tensorflow-serving/base_image_helper/.gitignore
- Curated-Apps/workloads/tensorflow-serving/base_image_helper/Dockerfile
- Curated-Apps/workloads/tensorflow-serving/base_image_helper/README.md
- Curated-Apps/workloads/tensorflow-serving/base_image_helper/helper.sh
- Curated-Apps/workloads/tensorflow-serving/insecure_args.txt
- Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template
- Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template
Updating the Curated script and packages to add tensorflow-serving.
Signed-off-by: Sonali Saha <sonali.saha@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/16)
> [Curated-Apps] Add tensorflow serving curation app example

- Curated-Apps/README.md
- Curated-Apps/workloads/pytorch/README.md
- Curated-Apps/workloads/pytorch/base_image_helper/README.md
- Curated-Apps/workloads/redis/README.md
- Curated-Apps/workloads/sklearn/README.md
- Curated-Apps/workloads/sklearn/base_image_helper/README.md
- Curated-Apps/workloads/tensorflow-serving/README.md
List of changes in PR:
1. Removed the `$`symbols from beginning of sh commands which helps in directly executing the commands after copying using copy button that appears at the right of `sh` block.
2. Added `tomli and tomli-w` packages to prerequisites which will be required when Curated-Apps start using GSC v1.4
3. Some prerequisite packages `torchvision, pillow, scikit-learn-intelex` for `Scikit-learn` and `PyTorch` apps are not available with default pip version on `ubuntu 18.04`. For this we need to upgrade pip version.
4. Added missing prerequisites step in `Pytorch` and `Scikit-learn` apps READMEs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/28)
> [Curated-Apps] Improvements in READMEs

- Curated-Apps/util/curation_script.sh
- Curated-Apps/workloads/mysql/.gitignore
- Curated-Apps/workloads/mysql/README.md
- Curated-Apps/workloads/mysql/base_image_helper/.gitignore
- Curated-Apps/workloads/mysql/base_image_helper/encrypted_files.txt
- Curated-Apps/workloads/mysql/docker_run_flags.txt
- Curated-Apps/workloads/mysql/insecure_args.txt
- Curated-Apps/workloads/mysql/mysql-gsc.dockerfile.template
- Curated-Apps/workloads/mysql/mysql.manifest.template
- Curated-Apps/workloads/pytorch/README.md
- Curated-Apps/workloads/pytorch/pytorch-gsc.dockerfile.template
- Curated-Apps/workloads/pytorch/pytorch.manifest.template
- Curated-Apps/workloads/redis/README.md
- Curated-Apps/workloads/redis/redis-gsc.dockerfile.template
- Curated-Apps/workloads/sklearn/README.md
- Curated-Apps/workloads/sklearn/sklearn.manifest.template
- Curated-Apps/workloads/tensorflow-serving/README.md
- Curated-Apps/workloads/tensorflow-serving/tensorflow-serving-gsc.dockerfile.template
- Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template
Curate MySQL server.
PR https://github.com/gramineproject/contrib/pull/39 is prerequisite for this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/40)
> [Curated-Apps] Add MySQL

- Curated-Apps/workloads/memcached/.gitignore
- Curated-Apps/workloads/memcached/README.md
- Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template
- Curated-Apps/workloads/memcached/memcached.manifest.template
Updating the Curated script and packages to add Memcached.
Currently, the PR is depending on PR #39.
Merging orders should be
PR #39
PR #35
Signed-off-by: Sonali Saha <sonali.saha@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/35)
> [Curated-Apps] Add memcached

- Intel-Confidential-Compute-for-X/util/constants.py
We have more text on Curated-Apps TUI as we are going to displaying workload specific input examples, hence need to increate the UI size and text box size for user inputs as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/51)
> [Curated-Apps] Increase TUI size to accomodate more text and user input

- Intel-Confidential-Compute-for-X/README.md
- Intel-Confidential-Compute-for-X/workloads/mariadb/.gitignore
- Intel-Confidential-Compute-for-X/workloads/mariadb/README.md
- Intel-Confidential-Compute-for-X/workloads/mariadb/base_image_helper/.gitignore
- Intel-Confidential-Compute-for-X/workloads/mariadb/base_image_helper/encrypted_files.txt
- Intel-Confidential-Compute-for-X/workloads/mariadb/docker_run_flags.txt
- Intel-Confidential-Compute-for-X/workloads/mariadb/insecure_args.txt
- Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb-gsc.dockerfile.template
- Intel-Confidential-Compute-for-X/workloads/mariadb/mariadb.manifest.template
Curate MariaDB server.
PR #39 is a prerequisite for this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/41)
> [Curated-Apps] Add MariaDB

- Intel-Confidential-Compute-for-X/README.md
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/.gitignore
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/base_image_helper/.gitignore
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/base_image_helper/encrypted_files.txt
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/client_requirements.txt
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/docker_run_flags.txt
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/insecure_args.txt
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server-gsc.dockerfile.template
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/openvino-model-server.manifest.template
Curate OpenVINO Model Server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/46)
> [Curated-Apps] Add OpenVINO Model Server

- Intel-Confidential-Compute-for-X/workloads/mariadb/README.md
- Intel-Confidential-Compute-for-X/workloads/memcached/README.md
- Intel-Confidential-Compute-for-X/workloads/mysql/README.md
- Intel-Confidential-Compute-for-X/workloads/openvino-model-server/README.md
- Intel-Confidential-Compute-for-X/workloads/pytorch/README.md
- Intel-Confidential-Compute-for-X/workloads/redis/README.md
- Intel-Confidential-Compute-for-X/workloads/sklearn/README.md
- Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md
Command used in test mode was broken after using the `argparse` for parsing the arguments. This PR fixes the commands for all the workloads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/62)
> [Curated-Apps] Fix command used in test mode

- Intel-Confidential-Compute-for-X/util/curation_script.sh
- Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template
- Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh
Currently Curated-Apps uses Gramine v1.5 version.
This PR move the Curated-Apps to use Gramine v1.6 version.
Fixes #63 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/68)
> [Curated-Apps] Move to Gramine v1.6

- Integrations/azure/ra_tls_maa/meson.build
- debian/changelog
- debian/control
Synces version numbers with Gramine release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/67)
> Release 1.6

- Intel-Confidential-Compute-for-X/README.md
- Intel-Confidential-Compute-for-X/util/curation_script.sh
- Intel-Confidential-Compute-for-X/workloads/mysql/README.md
- Intel-Confidential-Compute-for-X/workloads/pytorch/README.md
- Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md
- Intel-Confidential-Compute-for-X/workloads/redis/README.md
- Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/README.md
- Intel-Confidential-Compute-for-X/workloads/tensorflow-serving/README.md
README updates and removed references for Ubuntu 18.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/77)
> [Curated-apps] README updates

- Integrations/azure/ra_tls_maa/meson.build
- debian/changelog
- debian/control
Fixes #78
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/80)
> Release 1.6.1

- Integrations/azure/ra_tls_maa/meson.build
- Integrations/intel/ra_tls_ita/meson.build
- debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/86)
> Release 1.7
