- Curated-Apps/.gitignore
- Curated-Apps/README.md
- Curated-Apps/curate.py
- Curated-Apps/util/.gitignore
- Curated-Apps/util/config.yaml.template
- Curated-Apps/util/constants.py
- Curated-Apps/util/curation_script.sh
- Curated-Apps/verifier/.gitignore
- Curated-Apps/verifier/helper.sh
- Curated-Apps/verifier/verifier.dockerfile.template
- Curated-Apps/workloads/pytorch/.gitignore
- Curated-Apps/workloads/pytorch/README.md
- Curated-Apps/workloads/pytorch/base_image_helper/.gitignore
- Curated-Apps/workloads/pytorch/base_image_helper/Dockerfile
- Curated-Apps/workloads/pytorch/base_image_helper/README.md
- Curated-Apps/workloads/pytorch/base_image_helper/helper.sh
- Curated-Apps/workloads/pytorch/pytorch-gsc.dockerfile.template
- Curated-Apps/workloads/pytorch/pytorch.manifest.template
- Curated-Apps/workloads/redis/.gitignore
- Curated-Apps/workloads/redis/README.md
- Curated-Apps/workloads/redis/redis-gsc.dockerfile.template
- Curated-Apps/workloads/redis/redis.manifest.template
Signed-off-by: aneessahib <anees.a.sahib@intel.com>
This application will provide step-by-step guidance in creating your own custom containers protected by Gramine. 
The target deployment environment is assumed to be an Azure Confidential compute instance with out of tree DCAP driver. Following stages are involved in the GSC image curation:
- Distro Selection
- Enclave Signing Key
- Attestation
- Secret Provisioning
- Encrypted Files
- Environment Variables
- Runtime Arguments
- Execution & Debug
To test, execute in the below order
`$ sudo apt-get install jq`
`$ sudo apt-get install docker.io python3 python3-pip`
`$ pip3 install docker jinja2 toml pyyaml`
`$ python3 curate.py redis redis:7.0.0`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Add end to end GSC image curation tool

- Curated-Apps/curate.py
- Curated-Apps/util/config.yaml.template
- Curated-Apps/verifier/helper.sh
- Curated-Apps/verifier/verifier.dockerfile.template
Reverted the commit aa71356 used for workaround the packaging issue with gramine v1.3, enabled build logs which were hidden before and updated the latest gramine tag 1.3.1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/10)
> Reverted the commit aa71356 used for workaround the packaging issue

- Curated-Apps/util/curation_script.sh
Curation currently uses GSC latest master and with tomli changes, it breaks curation. This PR forces curation to use GSC 1.3.1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/15)
> [Curation] Use GSC 1.3.1 instead of latest master

- Curated-Apps/util/curation_script.sh
- Curated-Apps/workloads/pytorch/pytorch.manifest.template
- Curated-Apps/workloads/redis/redis.manifest.template
Current implementation missing support for command line arguments while generating non-production GSC image. This PR add support for command-line arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/18)
> [Curated Apps] Support insecure command-line args for test gsc images

- Curated-Apps/curate.py
- Curated-Apps/util/constants.py
As of now curation app doesn't have provision to input additional docker flags (--name, --rm, -p, etc.). Hence these flags cannot be added to the `docker run` commands generated by curation app in commands.txt. This PR provides option to input these flags which ultimately gets added to `docker run` instructions for running the curated images, please refer the attached screenshot for the UI related changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/13)
> [Curated-Apps] Add user inputs for additional docker run flags

- Curated-Apps/util/curation_script.sh
Redis run fails with below error:
```Error Produced:
*** FATAL CONFIG FILE ERROR (Redis 7.0.5) ***
Reading the configuration file, at line 3
>>> 'save "" ""'
Invalid save parameters
```
GSC retrieves arguments by reading the CMD instruction in docker base image. If CMD is empty, GSC add cmd instruction with double quotes like this `CMD[""]` which is passed by `apploader.sh` to `entry_script_redis.sh`
In case of Redis, generated `entry_script_redis.sh` have:
`docker-entrypoint.sh --protected-mode no --save ' ${@}`
during execution `${@} is translated to `""` and final `entry_script_redis.sh` look like:
`docker-entrypoint.sh --protected-mode no --save '' ""`
So extra `""` added by GSC when `CMD` instruction in base docker image is empty, causes the issue with redis. `CMD [""]` Generation in …
> [Curated-Apps] Workaround for empty instruction `CMD [""]` added by GSC

- Curated-Apps/curate.py
- Curated-Apps/util/constants.py
Fixes #26: Copying `docker run command` in test page that spills over to new line does not work.
Details: With current implementation, curses is used from start of the main function. curation app, at the end of image curation in test mode, prints the `docker run command` on screen which could spill over to next line. In this case when user copy the command from screen which spilled over to next line contains newline character `\n` which is wrong and doesn't work when executed.
Root cause: curses defines screen size and if something doesn't fit it add newline `\n` character and spill over the remaining contents to next line.
Fix in PR: Instead of using curses at the start of main, use curses only in `custom image creation` where we need UI.
- - -
This change is [<img …
> [Curated-Apps] Skip curses usage for test mode

- Curated-Apps/curate.py
- Curated-Apps/util/constants.py
- Curated-Apps/util/curation_script.sh
- Curated-Apps/workloads/pytorch/base_image_helper/encrypted_files.txt
Summary of the changes in PR:
1. Hard-code encryption key in the manifest when user opts to test without attestation. This is useful in cases where user wants to test encrypted files functionality without attestation.
2. Developers had to modify `curation_script.sh` everytime while curating new apps having encrypted files list in the base image in test mode. Now developers just have to create `encrypted_files` and add encrypted files to the file.
3. Old implementation use to prefix `PWD` to all the encypted files while creating mount point in manifest even if path is absolute. Now prefixing `PWD` is skipped if path is absolute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproj …
> [Curated-Apps] Add encryption key in the manifest for testing without attestation

- Curated-Apps/curate.py
To test debug build with remote attestation, verifier `docker run` command must have  `-e 
A_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 -e  RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1` environment variables.
These environment variables were missing for debug builds. This PR add them.
Fixes #32
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/33)
> [Curated-Apps] Add attestation env variables used with debug enclave

- Curated-Apps/workloads/tensorflow-serving/base_image_helper/Dockerfile
- Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template
This PR updates the TFS base image to use Ubuntu 20.04 (since Ubuntu 18.04 will be seeing EOL soon). It also updates the copyright header to 2023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/37)
> [Curated-Apps] Update Tensorflow base image to Ubuntu 20.04; Copyright to 2023

- Intel-Confidential-Compute-for-X/workloads/mysql/README.md
- Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/README.md
Some workloads uses latest version of gramine documentation which is broken now instead curated app should use the stable version.
This PR uses the stable version of gramine documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/48)
> [Curated-Apps] Update Gramine docs link

- Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/Dockerfile
- Intel-Confidential-Compute-for-X/workloads/sklearn/base_image_helper/kmeans_perf_eval.py
Currently used `bitnami/scikit-learn-intel` base image for scikit-learn curation is removed from dockerhub, hence scikit-learn curation is broken.
This PR uses `intel/intel-optimized-ml:scikit-learn-2023.1.1-xgboost-1.7.5-pip-base` as base image for scikit-learn curation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/50)
> [Curated-Apps] Change scikit-learn base image

- Intel-Confidential-Compute-for-X/curate.py
- Intel-Confidential-Compute-for-X/util/constants.py
1. Currently we display examples on curation UI for list of encrypted files for PyTorch even if workload type is not PyTorch, it's hard coded [here](https://github.com/gramineproject/contrib/blob/master/Curated-Apps/util/constants.py#L106).
2. Also examples are missing for other parameters e.g. `docker run flags`, `comman-line arguments` etc. This PR add workload specific examples on UI by reading all the parameters used in test mode.
3. Also increased the height of UI to accomodate more text on UI as well as in `user input` section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/42)
> [Curated-Apps] Display workload specific examples on UI

- Intel-Confidential-Compute-for-X/curate.py
- Intel-Confidential-Compute-for-X/util/constants.py
Currently user have to input distro of their base image for curation, also `ubuntu:18.04` distro is used in curation test mode for all the workloads which is wrong.
With this PR, distro is retrieved from the base image being curated automatically and used while durating it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/47)
> [Curated-Apps] Fetch distro from image and use with curation

- Intel-Confidential-Compute-for-X/util/curation_script.sh
We preload `libsecret_prov_attest.so` library if remote attestation is selected by user. But if `LD_PRELOAD` exists in workload specific manifest, then we will have two LD_PRELOAD which will result in `Duplicate Key` error.
This PR fixes this by concatenating the LD_PRELOAD with workload specific manifest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/53)
> [Curated-Apps] Concat LD_PRELOAD if exists in workload manifest file

- Intel-Confidential-Compute-for-X/workloads/mariadb/README.md
- Intel-Confidential-Compute-for-X/workloads/mysql/README.md
- Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/Dockerfile
- Intel-Confidential-Compute-for-X/workloads/redis/README.md
Redis, PyTorch, MySQL and MariaDB image tags are updated.
Redis 7.0.11 onwards is based on debian 12 which is not supported
in GSC yet, hence using 7.0.10 which is based on debian 11.
Memcached 1.6 onwards uses eventfd syscall which is insecure in
Gramine, hence keeping the current tag 1.5-20.04_beta.
TF-Serving is built locally and is latest based on Ubuntu:20.04.
OpenVINO Model Server and Sklearn already on latest tags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/54)
> [Curated-Apps] Use latest image tags

- Intel-Confidential-Compute-for-X/util/curation_script.sh
- Intel-Confidential-Compute-for-X/verifier/helper.sh
This PR fixes two issues as explained below:
1. Curation script doesn't exit immediatly on any error, we have seen it multiple cases when `gsc build` fails but curation proceed to next spte of signing the image. Added `set -e` to fix this.
2. Curation script executed by non-root user doesn't override the files `<workload>.manifest`, `<workload>-gsc.dockerfile` etc files  already created by root user `-f` with `cp` fixes that. Code lines: [here](https://github.com/gramineproject/contrib/blob/be92cdebc212e38690366aa7d7d3c2e2b78d86be/Intel-Confidential-Compute-for-X/util/curation_script.sh#L49-L50).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/55)
> [Curated-Apps] Exit curation script on error

- Intel-Confidential-Compute-for-X/README.md
- Intel-Confidential-Compute-for-X/curate.py
- Intel-Confidential-Compute-for-X/util/curation_script.sh
The `--debug` flag was recently removed from GSC and superseded by `--buildtype`.
This PR is to adapt the changes in GSC. Also now Curated-Apps uses `argparse` for processing the arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/60)
> [Curated-Apps] Use `--buildtype` instead of `--debug` in GSC

- Intel-Confidential-Compute-for-X/README.md
Fixes two issues:
1. Copying all command and executing does't work due to missing line-continuation character.
2. Registery update using command `sudo apt update` was missing because of which packages `libsgx-dcap-ql libsgx-dcap-default-qpl=1.16.100.2-focal1` installation fail.
This PR fixes above two issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/69)
> [Curated-Apps] Fix commands of installing build dependencies

- Intel-Confidential-Compute-for-X/workloads/mysql/README.md
Public key of old image is expired due to which package installation fails on old image during GSC build
Fixes #71 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/70)
> [Curated-Apps] Update MySQL image to the latest version

- Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-8.4.0/compile.sh
For minimization purposes, libcurl is built with most features disabled. One of the disabled features was proxy support. This made libcurl-based dependencies, such as RA-TLS libs, unusable in proxy-restricted environments (e.g. with a company-wide proxy). This commit re-enables proxy support, which increases the size of `libcurl.a` by ~7%.
This commit is the same as commit "[curl] Re-enable proxy support in libcurl" in the core Gramine repo. See https://github.com/gramineproject/gramine/pull/1720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/74)
> [Integrations/azure] Re-enable proxy support in libcurl

- Intel-Confidential-Compute-for-X/util/curation_script.sh
- Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template
With the new release of Gramine, old packages are replaced with new packages. Which causes verifier's build failure.
We always need a PR to fix it after every Gramine release.
With this PR, verifier will use latest Gramine packages and GSC version might not match with Gramine.
But for long term, we need to figure out a stable solution where we don't need such a PR after every Gramine release keeping Gramine and GSC versions same.
Please refer [PR#81](https://github.com/gramineproject/contrib/pull/81) for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/contrib/82)
> [Curated-Apps] Move to Gramine v1.6.1

- Intel-Confidential-Compute-for-X/util/curation_script.sh
- Intel-Confidential-Compute-for-X/verifier/verifier.dockerfile.template
- Intel-Confidential-Compute-for-X/workloads/pytorch/base_image_helper/helper.sh
With the new release of Gramine, old packages are replaced with new packages which use to cause verifier's build failure.
We always needed a PR to fix it after every Gramine release.
This issue was fixed partially with PR #82 where Gramine would use latest release package but GSC is still on old release.
Curated apps would still fail if GSC and Gramine versions are not same and also not compatible.
This PR tries to minimize the difference in releases of GSC and Gramine as latest tags are fetched automatically.
There could be the issue again if there is a time gap in creating the latest release tags for Gramine and GSC and in that time if a user curate the apps. We can think of placing a policy for creating Gramine and GSC tags at the same time.
After this PR, we won't need a contrib PR …
> [Curated-Apps] Auto fetch latest release tag

- Integrations/intel/ra_tls_ita/.gitignore
- Integrations/intel/ra_tls_ita/README.md
- Integrations/intel/ra_tls_ita/helpers/gramine-v1.6.2-ci-examples.patch
- Integrations/intel/ra_tls_ita/meson.build
- Integrations/intel/ra_tls_ita/src/ra_tls.map
- Integrations/intel/ra_tls_ita/src/ra_tls_verify_ita.c
- Integrations/intel/ra_tls_ita/src/secret_prov.map
- Integrations/intel/ra_tls_ita/src/secret_prov_verify_ita.c
- Integrations/intel/ra_tls_ita/subprojects
This commit adds the sources, documentation and tests for `libra_tls_verify_ita.so` and `libsecret_prov_verify_ita.so` libraries, used for integration of Gramine with Intel Trust Authority (ITA, formerly Project Amber).
The sources and the build system are largely based on the Microsoft Azure Attestation (MAA) RA-TLS libs found in the same repository. However, ITA turned out to have substantial differences from MAA, thus we decided to have separate sources for MAA and ITA (in contrast to e.g. creating ITA as a series of patches to MAA).
See for context:
- https://github.com/gramineproject/contrib/issues/73
- https://github.com/gramineproject/contrib/pull/59
Fixes #73
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [Integrations/intel] Add RA-TLS/SecretProv libs for ITA
